###jjkjk
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "fullName": "lavis",
  "confirmPassword": "Goole",
  "email": "Lavish85@gmail.com",
  "password": "Goole"
}

###find user by id
GET http://localhost:3000/auth/1

###Find user by email
GET http://localhost:3000/auth/?email=tonyawasthi85@gmail.com


###delete User
DELETE http://localhost:3000/auth/12345

###Upadte User
PATCH http://localhost:3000/auth/2777
Content-Type: application/json


###login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "Lavish85@gmail.com",
  "password": "Goole"
}
 

###task creation
POST http://localhost:3000/tasks/taskcreation
Content-Type: application/json

{
  "title": "Develop User Authentication",
  "description": "Implement login and registration functionalities with JWT authentication.",
  "status": "nmnm"
}



###Comment creation
POST http://localhost:3000/comments/create
Content-Type: application/json

{
   
  "comment": "This is a test comment"
}
